### ISSUE TITLE
Responsive issue in professor section 

### ISSUE THREAD

**Issue by skanarul8002** [skanarul8002/mca-hub#11]
Check deploy URL with provided credentials

**Comment by n-keerthi-gayathri** [comment]
@skanarul8002 please assign me this issue

**Comment by skanarul8002** [comment]
Ok sure @n-keerthi-gayathri . You must star ⭐ the repository first before contributing

**Comment by n-keerthi-gayathri** [comment]
please specify what are the components that you need to be responsive @skanarul8002

**Comment by skanarul8002** [comment]
Please @n-keerthi-gayathri, go through the URL and choose at least one section that you can select and work on.
Like 👇
![Screenshot_20241012_154803](https://github.com/user-attachments/assets/5485b28e-8a8c-496c-8852-72e6051d783d)
Hope you understand.

**Comment by n-keerthi-gayathri** [comment]
Before:
![image](https://github.com/user-attachments/assets/cf5cf71c-751b-412e-b73f-d169fb340283)
After:
![image](https://github.com/user-attachments/assets/920cac89-6c84-4412-ae1f-058dcf287c92)

Shall i raise a PR?

**Comment by skanarul8002** [comment]
Please, @n-keerthi-gayathri , check the UI in MP as well.

**Comment by n-keerthi-gayathri** [comment]
`
![Screenshot 2024-10-13 162115](https://github.com/user-attachments/assets/facd1fed-7d78-4c17-a39c-99a2655fa966)
`
this is the mobile view

**Comment by n-keerthi-gayathri** [comment]
![Screenshot 2024-10-13 162115](https://github.com/user-attachments/assets/ccaab4af-14ac-4ebc-84e6-1a3c877c2f0a)
here is the mobile view

**Comment by skanarul8002** [comment]
Good work @n-keerthi-gayathri, please generate PR then I will verify your work in live url.

**Comment by n-keerthi-gayathri** [comment]
> Good work @n-keerthi-gayathri, please generate PR then I will verify your work in live url.

yes i have raised a PR, merge it to see the changes

**Comment by skanarul8002** [comment]
@n-keerthi-gayathri , please solve this issues also.
![image](https://github.com/user-attachments/assets/87a58a3a-c981-4ef4-b7d0-e1f4b169eb59)

**Comment by n-keerthi-gayathri** [comment]
![image](https://github.com/user-attachments/assets/5672dbe4-2215-47e9-b20f-5aee155166d0)
once check this

**Comment by skanarul8002** [comment]
yeah good jobs. raise pr @n-keerthi-gayathri

**Comment by n-keerthi-gayathri** [comment]
@skanarul8002 i want to make them responsive

-Admin/classes

-Admin/subjects

-Admin/teachers

**Comment by skanarul8002** [comment]
@n-keerthi-gayathri, please comment on correct issue. this issues related to professor section
