### ISSUE TITLE
Forgot Password Functionality

### ISSUE THREAD

**Issue by skanarul8002** [skanarul8002/mca-hub#2]
need to work on forgot password functionality
![image](https://github.com/user-attachments/assets/de61d8c2-7e0d-4361-aefc-f99ed9cab93a)

**Comment by Rehannn03** [comment]
Hey @skanarul8002 can you assign this to me

**Comment by skanarul8002** [comment]
Go ahead @Rehannn03

**Comment by skanarul8002** [comment]
any update @Rehannn03

**Comment by Rehannn03** [comment]
On it @skanarul8002 almost done will create a pull request for it by EOD.

**Comment by skanarul8002** [comment]
Good work.... please fetched updated repo and modify on it. Due to some contributor's this project is not run correctly but I updated Mca hub code yesterday night. So please check it.
Or//
 raise pr with stage change file Only.
I think you are working on backend side so no problem. You raise your pr
