### ISSUE TITLE
put your first issues in hacktoberfest

### ISSUE THREAD

**Issue by skanarul8002** [skanarul8002/mca-hub#23]
browse deployed url + find issues and read readme file

**Comment by Rehannn03** [comment]
@skanarul8002 Greetings!
If any backend related work is there please feel free to raise the issue and assign it to me!!

**Comment by skanarul8002** [comment]
Sure @Rehannn03 , if you're interested in backend development, please work on the 'Forgot Password' feature. It should send a verification email to the respective admin, student, or professor, allowing them to update only their password.

Remember there have role based permission and access control.
![image](https://github.com/user-attachments/assets/8fc1bd02-c4fc-454c-8a54-f2a8dc85fb46)

**Comment by Rehannn03** [comment]
Ok sure.
Thanks.
I will work on this and attach it with issue number #2 and then raise a PR.

**Comment by Rehannn03** [comment]
Can you assign issue #2 to me?
