### ISSUE TITLE
[Enhancement] Navbar not being mobile user friendly 

### ISSUE THREAD

**Issue by yolk23** [skanarul8002/mca-hub#33]
**Description**
Navbar can be improved by having a burger icon then dropping down a modal when the user clicks on it. 
![image](https://github.com/user-attachments/assets/1acfd392-1c9b-4a6c-89a8-41b8be963433)

**Comment by skanarul8002** [comment]
@shubhamkumaar , please find another issue on my portfolio repo(https://github.com/skanarul8002/Portfolio/). this is help full for other contributors.
