### ISSUE TITLE
Dynamic Profile of Student

### ISSUE THREAD

**Issue by skanarul8002** [skanarul8002/mca-hub#4]
In mca_hub, student profile's first section is dynamic but second below section is hard coded. So need to dynamic it by filling the all details on the register form.
![image](https://github.com/user-attachments/assets/40e3bf38-5fa5-4dc2-a878-6c3110fabd58)

**Comment by shubhamkumaar** [comment]
Bro can you share your .env and mongo it will help me to work on this project quickly.

**Comment by skanarul8002** [comment]
Ok sure @shubhamkumaar
Frontend/ .env: REACT_APP_BASE_URL=http://localhost:8081
Backend/env: 
PORT=8081
MONGO_URL= you can use local MongoDB URL here
Step:  register admin first and then adds student through admin then login as student
