### ISSUE TITLE
Adding Forgot password functionality in Frontend

### ISSUE THREAD

**Issue by Rehannn03** [skanarul8002/mca-hub#45]
The forget password functionality is already added in the backend
Implement it in the frontend
@skanarul8002 Please assign this to me

**Comment by skanarul8002** [comment]
Mention with good comments into the code

**Comment by MD-Rahed-Mia** [comment]
Can I do it?

**Comment by skanarul8002** [comment]
@MD-Rahed-Mia , already assigned. Please check another good issue

**Comment by skanarul8002** [comment]
@Rehannn03 , any update. do fast

**Comment by Rehannn03** [comment]
50% work is completed. On it!

**Comment by Rehannn03** [comment]
Can you please give me backend deployed URL?

**Comment by skanarul8002** [comment]
yeah,  REACT_APP_BASE_URL = https://mca-hub.onrender.com

**Comment by Rehannn03** [comment]
Everythings is working fine on localhost.
But as soon as I try to test using this url: https://mca-hub.onrender.com/ it doesnt work for /Admin/resetPasswordLink
And gives error Cannot POST /Admin/resetPasswordLink.

So please look into that.
Anyways I've made the forget password functionality in frontend and works fine.

Thank you!
